version: '3'

services:
  nginx:
    image: nginx:latest
    volumes:
      - .:/app
      - .docker/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '8080:80'
    links:
      - php

  php:
    build: .docker/php-fpm
    volumes:
      - .:/app
#    links:
#      - db
#
#  db:
#    image: postgres
#    ports:
#      - '5432:5432'
#    environment:
#      POSTGRES_DB: symfony
#      POSTGRES_USER: symfony
#      POSTGRES_PASSWORD: symfony
#    volumes:
#      - db-data:/var/lib/postgresql/data
#
#  maildev:
#    image: djfarrelly/maildev
#    ports:
#      - '1080:80'
#
#volumes:
#  db-data: